import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, '..');

let content = fs.readFileSync(path.join(rootDir, 'recovery/snapshot_v3.1.1/js/store.js'), 'utf8');

// 1. Replace APP_CREATOR
const appCreatorReplacement = [
  "export const APP_CREATOR = Object.freeze(Object.assign(",
  "  new String('FChNeto'),",
  "  {",
  "    name: 'FChNeto',",
  "    signature: 'Criado por FChNeto',",
  "    role: 'Criador e Desenvolvedor',",
  "    app: 'Finanças Pediatria',",
  "    immutable: true,",
  "    toString: () => 'FChNeto',",
  "    valueOf: () => 'FChNeto',",
  "    [Symbol.toPrimitive]: () => 'FChNeto'",
  "  }",
  "));",
  "",
  "export const APP_VERSION = '4.0.0';",
  "export const DB_NAME = 'v4_pediatric_cloud_db';",
  "export const DB_STORE = 'app_state';",
  "",
  "export const CANONICAL_CATEGORIES = [",
  "  'Passagens', 'Mercantil', 'Academia', 'Estudo', 'Cursos', 'Presentes',",
  "  'Aluguel', 'Energia', 'Internet', 'Combustível', 'Qualificação/Congresso/Pós',",
  "  'Cosméticos', 'Água', 'Lanches', 'Doação', 'Refeição', 'Beleza/Salão',",
  "  'Uber', 'Remédios', 'Compras Parceladas', 'Saídas', 'Delivery', 'Produtos de beleza'",
  "];",
  "",
  "export const DEFAULT_CATEGORIES = [",
  "  { id: 'cat_passagens', name: 'Passagens', icon: 'flight', color: '#7E57C2' },",
  "  { id: 'cat_mercantil', name: 'Mercantil', icon: 'cart', color: '#26A69A' },",
  "  { id: 'cat_academia', name: 'Academia', icon: 'fitness', color: '#EC407A' },",
  "  { id: 'cat_estudo', name: 'Estudo', icon: 'study', color: '#42A5F5' },",
  "  { id: 'cat_cursos', name: 'Cursos', icon: 'course', color: '#5C6BC0' },",
  "  { id: 'cat_presentes', name: 'Presentes', icon: 'gift', color: '#AB47BC' },",
  "  { id: 'cat_aluguel', name: 'Aluguel', icon: 'home', color: '#EF5350' },",
  "  { id: 'cat_energia', name: 'Energia', icon: 'bolt', color: '#FFA726' },",
  "  { id: 'cat_internet', name: 'Internet', icon: 'wifi', color: '#29B6F6' },",
  "  { id: 'cat_combustivel', name: 'Combustível', icon: 'fuel', color: '#FF7043' },",
  "  { id: 'cat_qualificacao', name: 'Qualificação/Congresso/Pós', icon: 'qualification', color: '#8E24AA' },",
  "  { id: 'cat_cosmeticos', name: 'Cosméticos', icon: 'cosmetics', color: '#F06292' },",
  "  { id: 'cat_agua', name: 'Água', icon: 'water', color: '#26C6DA' },",
  "  { id: 'cat_lanches', name: 'Lanches', icon: 'snack', color: '#FFCA28' },",
  "  { id: 'cat_doacao', name: 'Doação', icon: 'donation', color: '#E91E63' },",
  "  { id: 'cat_refeicao', name: 'Refeição', icon: 'meal', color: '#FF8A65' },",
  "  { id: 'cat_beleza_salao', name: 'Beleza/Salão', icon: 'beauty', color: '#D81B60' },",
  "  { id: 'cat_uber', name: 'Uber', icon: 'car', color: '#78909C' },",
  "  { id: 'cat_remedios', name: 'Remédios', icon: 'meds', color: '#66BB6A' },",
  "  { id: 'cat_compras_parceladas', name: 'Compras Parceladas', icon: 'credit_card', color: '#8D6E63' },",
  "  { id: 'cat_saidas', name: 'Saídas', icon: 'outing', color: '#9C27B0' },",
  "  { id: 'cat_delivery', name: 'Delivery', icon: 'delivery', color: '#FF5722' },",
  "  { id: 'cat_produtos_beleza', name: 'Produtos de beleza', icon: 'sparkles', color: '#F48FB1' }",
  "];",
  "",
  "export const MACRO_GROUPS = [",
  "  {",
  "    id: 'macro_alimentacao',",
  "    name: 'Alimentação',",
  "    aliases: ['Alimentação & Mercado', 'Alimentacao'],",
  "    icon: 'meal',",
  "    color: '#FF7043',",
  "    bgColor: '#FBE9E7',",
  "    categories: ['Mercantil', 'Refeição', 'Lanches', 'Delivery', 'Alimentação']",
  "  },",
  "  {",
  "    id: 'macro_transporte',",
  "    name: 'Transporte & Mobilidade',",
  "    aliases: ['Transporte & Logística', 'Transporte'],",
  "    icon: 'car',",
  "    color: '#42A5F5',",
  "    bgColor: '#E3F2FD',",
  "    categories: ['Combustível', 'Uber', 'Passagens', 'Transporte', 'Combustível/Plantão']",
  "  },",
  "  {",
  "    id: 'macro_moradia',",
  "    name: 'Moradia & Contas',",
  "    aliases: ['Moradia'],",
  "    icon: 'home',",
  "    color: '#26A69A',",
  "    bgColor: '#E0F2F1',",
  "    categories: ['Aluguel', 'Energia', 'Água', 'Internet', 'Lar']",
  "  },",
  "  {",
  "    id: 'macro_formacao',",
  "    name: 'Formação & Carreira',",
  "    aliases: ['Educação & Carreira', 'Formação', 'Educacao', 'Educação'],",
  "    icon: 'qualification',",
  "    color: '#7E57C2',",
  "    bgColor: '#EDE7F6',",
  "    categories: ['Estudo', 'Cursos', 'Qualificação/Congresso/Pós', 'Educação', 'Congresso & Atualização', 'CRM/RQE/SBP']",
  "  },",
  "  {",
  "    id: 'macro_saude_beleza',",
  "    name: 'Saúde & Autocuidado',",
  "    aliases: ['Saúde & Bem-EStar', 'Saúde', 'Saude'],",
  "    icon: 'sparkles',",
  "    color: '#EC407A',",
  "    bgColor: '#FCE4EC',",
  "    categories: ['Remédios', 'Academia', 'Cosméticos', 'Beleza/Salão', 'Produtos de beleza', 'Beleza', 'Saúde']",
  "  },",
  "  {",
  "    id: 'macro_lazer_outros',",
  "    name: 'Pessoal, Lazer & Outros',",
  "    aliases: ['Estilo de Vida & Outros', 'Lazer & Outros', 'Outros', 'Lazer'],",
  "    icon: 'gift',",
  "    color: '#AB47BC',",
  "    bgColor: '#F3E5F5',",
  "    categories: ['Presentes', 'Saídas', 'Compras Parceladas', 'Doação', 'Lazer', 'Viagens', 'Brinquedos/Materiais Lúdicos', 'Consultório/Sublocação', 'Impostos & Contabilidade', 'Contador', 'Outros']",
  "  }",
  "];",
  "",
  "export const MACRO_GROUPS_RECORD = {",
  "  'Alimentação': ['Mercantil', 'Refeição', 'Lanches', 'Delivery', 'Alimentação'],",
  "  'Transporte & Mobilidade': ['Combustível', 'Uber', 'Passagens', 'Transporte', 'Combustível/Plantão'],",
  "  'Moradia & Contas': ['Aluguel', 'Energia', 'Água', 'Internet', 'Lar'],",
  "  'Formação & Carreira': ['Estudo', 'Cursos', 'Qualificação/Congresso/Pós', 'Educação', 'Congresso & Atualização', 'CRM/RQE/SBP'],",
  "  'Saúde & Autocuidado': ['Remédios', 'Academia', 'Cosméticos', 'Beleza/Salão', 'Produtos de beleza', 'Beleza', 'Saúde'],",
  "  'Pessoal, Lazer & Outros': ['Presentes', 'Saídas', 'Compras Parceladas', 'Doação', 'Lazer', 'Viagens', 'Brinquedos/Materiais Lúdicos', 'Consultório/Sublocação', 'Impostos & Contabilidade', 'Contador', 'Outros']",
  "};",
  "",
  "export function getMacroGroupForCategory(categoryName) {",
  "  if (!categoryName || typeof categoryName !== 'string') return MACRO_GROUPS[5];",
  "  const trimmed = categoryName.trim();",
  "  for (const mg of MACRO_GROUPS) {",
  "    if (mg.categories.some(c => c.toLowerCase() === trimmed.toLowerCase())) {",
  "      return mg;",
  "    }",
  "  }",
  "  const lower = trimmed.toLowerCase();",
  "  if (lower.includes('aliment') || lower.includes('mercad') || lower.includes('lanche') || lower.includes('refeic') || lower.includes('delivery')) return MACRO_GROUPS[0];",
  "  if (lower.includes('transp') || lower.includes('combust') || lower.includes('uber') || lower.includes('passag')) return MACRO_GROUPS[1];",
  "  if (lower.includes('morad') || lower.includes('alug') || lower.includes('energ') || lower.includes('agua') || lower.includes('água') || lower.includes('inter')) return MACRO_GROUPS[2];",
  "  if (lower.includes('estud') || lower.includes('curs') || lower.includes('congres') || lower.includes('pos') || lower.includes('pós') || lower.includes('crm') || lower.includes('educa')) return MACRO_GROUPS[3];",
  "  if (lower.includes('saude') || lower.includes('saúde') || lower.includes('medic') || lower.includes('remed') || lower.includes('reméd') || lower.includes('acad') || lower.includes('belez') || lower.includes('cosmet')) return MACRO_GROUPS[4];",
  "  return MACRO_GROUPS[5];",
  "}",
  "",
  "export function addMonthsToDateString(dateStr, monthsToAdd) {",
  "  return addMonths(dateStr, monthsToAdd);",
  "}",
  "",
  "export function generateExpenseInstallments(baseExpense, totalInstallments) {",
  "  const installments = [];",
  "  const totalVal = Number(baseExpense.value || baseExpense.amount) || 0;",
  "  const numInst = Number(totalInstallments) || 1;",
  "  const instVal = Math.floor((totalVal / numInst) * 100) / 100;",
  "  const remainder = Math.round((totalVal - (instVal * numInst)) * 100) / 100;",
  "  const baseDate = baseExpense.dueDate || baseExpense.date || getLocalDateString();",
  "  for (let i = 1; i <= numInst; i++) {",
  "    const dueDate = addMonths(baseDate, i - 1);",
  "    const val = i === 1 ? Math.round((instVal + remainder) * 100) / 100 : instVal;",
  "    installments.push({",
  "      ...baseExpense,",
  "      id: (baseExpense.id || 'exp') + '_inst_' + i,",
  "      description: (baseExpense.description || 'Despesa') + ' (' + i + '/' + numInst + ')',",
  "      value: val,",
  "      amount: val,",
  "      dueDate,",
  "      date: dueDate,",
  "      installmentNumber: i,",
  "      totalInstallments: numInst,",
  "      isInstallment: true,",
  "      isPaid: i === 1 ? Boolean(baseExpense.isPaid) : false",
  "    });",
  "  }",
  "  return installments;",
  "}"
].join('\n');

content = content.replace(
  /export const APP_CREATOR = Object\.freeze\(\{[\s\S]*?\}\);/,
  appCreatorReplacement
);

// 2. Fix calculateShiftInstallments
const calcInstReplacement = [
  "export function calculateShiftInstallments(shiftDate, netValue, customPaymentDate = null) {",
  "  const numNet = Number(netValue) || 0;",
  "  if (customPaymentDate && typeof customPaymentDate === 'string' && customPaymentDate.trim() !== '') {",
  "    return [",
  "      {",
  "        number: 1,",
  "        percent: 100,",
  "        percentage: 100,",
  "        dueDate: customPaymentDate.trim(),",
  "        expectedDate: customPaymentDate.trim(),",
  "        value: numNet,",
  "        status: 'pending',",
  "        paidDate: null",
  "      }",
  "    ];",
  "  }",
  "  const d60 = addMonths(shiftDate, 2);",
  "  const d90 = addMonths(shiftDate, 3);",
  "  const part1 = Math.round(numNet * 0.75 * 100) / 100;",
  "  const part2 = Math.round((numNet - part1) * 100) / 100;",
  "  return [",
  "    {",
  "      number: 1,",
  "      percent: 75,",
  "      percentage: 75,",
  "      dueDate: d60,",
  "      expectedDate: d60,",
  "      value: part1,",
  "      status: 'pending',",
  "      paidDate: null",
  "    },",
  "    {",
  "      number: 2,",
  "      percent: 25,",
  "      percentage: 25,",
  "      dueDate: d90,",
  "      expectedDate: d90,",
  "      value: part2,",
  "      status: 'pending',",
  "      paidDate: null",
  "    }",
  "  ];",
  "}"
].join('\n');

content = content.replace(
  /export function calculateShiftInstallments[\s\S]*?\n\}/,
  calcInstReplacement
);

// 3. Ensure DEFAULT_HOSPITALS
const defaultLocs = [
  "export const DEFAULT_WORK_LOCATIONS = [",
  "  'Maternidade Araken',",
  "  'Maternidade Leide Morais',",
  "  'MEJEC',",
  "  'Hospital Infantil Sabará',",
  "  'Maternidade Pro Matre',",
  "  'Hospital Infantil São Lucas',",
  "  'PS Infantil Menino Jesus',",
  "  'Maternidade Santa Joana',",
  "  'Do meu Coração'",
  "];",
  "",
  "export const DEFAULT_HOSPITALS = DEFAULT_WORK_LOCATIONS;"
].join('\n');

content = content.replace(
  /export const DEFAULT_WORK_LOCATIONS = \[[\s\S]*?\];/,
  defaultLocs
);

// 4. Update getInitialData
const initialDataReplacement = [
  "export function getInitialData() {",
  "  return {",
  "    version: APP_VERSION,",
  "    creator: 'FChNeto',",
  "    doctorName: DEFAULT_DOCTOR_NAME,",
  "    doctorTitle: DEFAULT_DOCTOR_TITLE,",
  "    doctorCrm: 'CRM-SP • Pediatria',",
  "    doctorPhoto: null,",
  "    monthlyBudgetLimit: 10000,",
  "    monthlyIncomeGoal: 25000,",
  "    currentEquity: 150000,",
  "    hospitals: [...DEFAULT_WORK_LOCATIONS],",
  "    workLocations: [...DEFAULT_WORK_LOCATIONS],",
  "    workTypes: [...DEFAULT_WORK_TYPES],",
  "    activeWorkTypes: ['Plantão em Maternidade', 'Plantão em Hospital', 'Serviço Público'],",
  "    customExpenseCategories: [],",
  "    defaultTaxRate: 15,",
  "    residencySalary: {",
  "      active: true,",
  "      description: 'Salário Residência Médica (MEC)',",
  "      value: 4106.09,",
  "      dayOfMonth: 5",
  "    },",
  "    fixedSalaries: [],",
  "    shifts: [],",
  "    expenses: [],",
  "    consultations: [],",
  "    trash: []",
  "  };",
  "}"
].join('\n');

content = content.replace(
  /export function getInitialData\(\) \{[\s\S]*?\n\}/,
  initialDataReplacement
);

// 5. In addShift, populate installment1 and installment2
const addShiftSnippet = [
  "      installment1: (installments && installments[0]) ? {",
  "        number: 1,",
  "        percentage: installments[0].percent,",
  "        percent: installments[0].percent,",
  "        expectedDate: installments[0].dueDate,",
  "        dueDate: installments[0].dueDate,",
  "        value: installments[0].value,",
  "        status: installments[0].status,",
  "        paidDate: installments[0].paidDate",
  "      } : null,",
  "      installment2: (installments && installments[1]) ? {",
  "        number: 2,",
  "        percentage: installments[1].percent,",
  "        percent: installments[1].percent,",
  "        expectedDate: installments[1].dueDate,",
  "        dueDate: installments[1].dueDate,",
  "        value: installments[1].value,",
  "        status: installments[1].status,",
  "        paidDate: installments[1].paidDate",
  "      } : null,"
].join('\n');

content = content.replace(
  /const newShift = \{[\s\S]*?status: shift\.status \|\| "pending",/,
  (match) => match + '\n' + addShiftSnippet
);

// 6. Extra methods
const extraMethods = [
  "",
  "  saveShift(shift) {",
  "    const shiftDate = shift.shiftDate || shift.date || getLocalDateString(new Date());",
  "    const grossVal = Number(shift.grossValue !== undefined ? shift.grossValue : (shift.value || shift.netValue || 0)) || 0;",
  "    const netVal = Number(shift.netValue !== undefined ? shift.netValue : grossVal) || 0;",
  "    return this.addShift({",
  "      ...shift,",
  "      shiftDate,",
  "      date: shiftDate,",
  "      grossValue: grossVal || netVal,",
  "      netValue: netVal,",
  "      value: netVal",
  "    });",
  "  }",
  "",
  "  saveExpense(expense) {",
  "    const dueDate = expense.dueDate || expense.date || getLocalDateString(new Date());",
  "    const isInst = Boolean(expense.isInstallment);",
  "    const totalInsts = Number(expense.totalInstallments) || (isInst ? 3 : 1);",
  "    const totalVal = Number(expense.value || expense.amount) || 0;",
  "    if (isInst && totalInsts > 1) {",
  "      const instVal = Math.floor((totalVal / totalInsts) * 100) / 100;",
  "      const remainder = Math.round((totalVal - (instVal * totalInsts)) * 100) / 100;",
  "      const createdList = [];",
  "      for (let i = 1; i <= totalInsts; i++) {",
  "        const d = addMonths(dueDate, i - 1);",
  "        const curVal = i === 1 ? Math.round((instVal + remainder) * 100) / 100 : instVal;",
  "        const newExp = this.addExpense({",
  "          ...expense,",
  "          id: undefined,",
  "          description: (expense.description || 'Despesa') + ' (' + i + '/' + totalInsts + ')',",
  "          value: curVal,",
  "          dueDate: d,",
  "          date: d,",
  "          isInstallment: true,",
  "          installmentNumber: i,",
  "          totalInstallments: totalInsts,",
  "          isPaid: i === 1 ? Boolean(expense.isPaid) : false",
  "        });",
  "        createdList.push(newExp);",
  "      }",
  "      return createdList[0];",
  "    }",
  "    return this.addExpense({",
  "      ...expense,",
  "      dueDate,",
  "      date: dueDate,",
  "      value: totalVal",
  "    });",
  "  }",
  "",
  "  updateResidencySalary({ value, active = true, description = 'Salário Residência Médica (MEC)', dayOfMonth = 5 }) {",
  "    const numVal = Number(value) || 0;",
  "    this.data.residencySalary = {",
  "      active: Boolean(active),",
  "      value: numVal,",
  "      description,",
  "      dayOfMonth",
  "    };",
  "    this.upsertFixedSalary({",
  "      description,",
  "      value: numVal,",
  "      dayOfMonth",
  "    });",
  "    this.save();",
  "    return this.data.residencySalary;",
  "  }",
  "",
  "  getMonthSummary(monthStr, mode = 'caixa') {",
  "    const report = this.getMonthlyReport(monthStr);",
  "    const residencyIncome = (this.data.residencySalary && this.data.residencySalary.value)",
  "      ? Number(this.data.residencySalary.value)",
  "      : (this.data.fixedSalaries && this.data.fixedSalaries[0] ? Number(this.data.fixedSalaries[0].value) : 0);",
  "    const shiftIncome = mode === 'competencia' ? report.competencia.shiftsNetProduction : report.caixa.shiftsTotalNet;",
  "    const totalIncome = residencyIncome + shiftIncome;",
  "    const totalExpenses = report.expenses.total;",
  "    const balance = totalIncome - totalExpenses;",
  "    const macroTotals = {};",
  "    (report.expenses.list || []).forEach(e => {",
  "      const mg = getMacroGroupForCategory(e.category);",
  "      const val = Number(e.value || e.amount) || 0;",
  "      macroTotals[mg.name] = (macroTotals[mg.name] || 0) + val;",
  "    });",
  "    const macroBreakdown = Object.keys(macroTotals).map(name => {",
  "      const val = macroTotals[name];",
  "      const mg = MACRO_GROUPS.find(m => m.name === name) || MACRO_GROUPS[5];",
  "      return {",
  "        id: mg.id,",
  "        name: mg.name,",
  "        icon: mg.icon,",
  "        color: mg.color,",
  "        bgColor: mg.bgColor,",
  "        value: val,",
  "        percentage: totalExpenses > 0 ? Math.round((val / totalExpenses) * 100) : 0",
  "      };",
  "    });",
  "    return {",
  "      monthStr,",
  "      residencyIncome,",
  "      shiftIncome,",
  "      totalIncome,",
  "      totalExpenses,",
  "      balance,",
  "      macroBreakdown",
  "    };",
  "  }",
  "",
  "  exportBackupJsonString() {",
  "    return JSON.stringify({",
  "      version: APP_VERSION,",
  "      creator: APP_CREATOR.name,",
  "      app: 'Finanças Pediatria',",
  "      exportedAt: new Date().toISOString(),",
  "      data: this.data",
  "    }, null, 2);",
  "  }",
  "",
  "  resetData(mode = 'transactions_only') {",
  "    if (mode === 'transactions_only') {",
  "      this.data.shifts = [];",
  "      this.data.expenses = [];",
  "      this.data.consultations = [];",
  "      this.data.trash = [];",
  "    } else {",
  "      this.resetToDefault();",
  "    }",
  "    this.save();",
  "  }",
  "",
  "  importBackupFromFile(jsonString) {",
  "    try {",
  "      const parsed = typeof jsonString === 'string' ? JSON.parse(jsonString) : jsonString;",
  "      const importedData = parsed.data || parsed;",
  "      this.data = Object.assign(getInitialData(), importedData);",
  "      this.save();",
  "      return { success: true, count: (this.data.shifts.length + this.data.expenses.length) };",
  "    } catch (err) {",
  "      return { success: false, error: err.message };",
  "    }",
  "  }",
  "",
  "  updateDoctorProfile(profile = {}) {",
  "    if (profile.doctorName !== undefined) this.data.doctorName = profile.doctorName;",
  "    if (profile.doctorTitle !== undefined) this.data.doctorTitle = profile.doctorTitle;",
  "    if (profile.crm !== undefined) this.data.crm = profile.crm;",
  "    if (profile.specialty !== undefined) this.data.specialty = profile.specialty;",
  "    if (profile.doctorPhoto !== undefined) this.data.doctorPhoto = profile.doctorPhoto;",
  "    if (profile.monthlyBudgetLimit !== undefined) this.data.monthlyBudgetLimit = Number(profile.monthlyBudgetLimit);",
  "    if (profile.monthlyIncomeGoal !== undefined) this.data.monthlyIncomeGoal = Number(profile.monthlyIncomeGoal);",
  "    if (profile.salaryValue !== undefined) {",
  "      if (!this.data.residencySalary) this.data.residencySalary = { active: true, value: 0 };",
  "      this.data.residencySalary.value = Number(profile.salaryValue);",
  "    }",
  "    this.save();",
  "  }"
].join('\n');

content = content.replace(
  /\n  \}\n\}\n\n\/\/ Standalone Helper/,
  '\n  }' + extraMethods + '\n}\n\n// Standalone Helper'
);

fs.writeFileSync(path.join(rootDir, 'js/store.js'), content, 'utf8');
console.log('js/store.js generated successfully');
